### ISSUE TITLE
Remove on double tap deletes written rpub and pdf pages

### ISSUE THREAD

**Issue by Potjoe-97** [mb1986/rm-hacks#159]
Hi! 

Running some tests with 0.0.9 alpha 4. I noticed that the centered double tap deletes pdf and epub pages. They seemed to be considered as "empty pages" despite the fact that there is text on them.

Step to reproduce : open a pdf file, double tap on a written page

**Comment by dreadful-brain** [comment]
I've tested with alpha5:

- Adding and removing on Notebooks works perfectly.
- On epub and pdf there is a small issue when adding and removing pages at the end, After removing the last page it jumps one more page, example:

1. PDF with 1800 pages
2. Double tap right adds new page and goes to 1801
3. Swipe left removes page 1801 because its empty but then moves to page 1799

But everything else works as expected.

How do you decide that the last page on a pdf or epub can get removed?
You correctly only remove really empty pages (with no pdf content) and not pdf content with no scribble.
I think the same condition could be applied to the double tap to make sure that it only removes empty pages added by user and not unscribbled pdf content, what do you think?

**Comment by atngames** [comment]
Yes I am going to refine it next week probably

**Comment by atngames** [comment]
I think this has been corrected in a previous alpha, I can not reproduce this bug.
