### ISSUE TITLE
Alternative checksum for 3.9.3.1986

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [mb1986/rm-hacks#163]
Hi there. I wanted to try to install the latest version of rm-hacks, and despite the tablet clearly indicating I'm on 3.9.3.1986; the rm-hacks installer shows an error due to not detecting suitable patches for `2bedac50b1ac38d483a01973421f5b009c98dbec`. Did I get a weird checksum, or do I have a “shiny” update?
I did try to add my version forcefully to the list of supported checksum, but I had issues downloading the needed files due to certificate and `Connection reset by peer` errors with it.

**Comment by Eeems** [comment]
rM1 or rM2?

**Comment by PoorPocketsMcNewHold** [comment]
rM2

-------- Message d'origine --------

**Comment by Eeems** [comment]
Have you updated your OS since you got it? Or did it comes with 3.9.3 installed?

What has happened in the past is that two different versions of the OS update were being served by the official servers. Of which, one was a bad file and had minor data corruption. This caused some issues in the past for people installing ddvk-hacks for the exact same reason as is happening here. The sha256sum for the xochitl application didn't match what was expected.

**Comment by PoorPocketsMcNewHold** [comment]
Oh, I assume it might be that. It was a refurbished tablet after all. Either way, I've updated it to 3.9.1991 either since.
