### ISSUE TITLE
Move "Clear clipboard" bar to another position

### ISSUE THREAD

**Issue by plan5** [mb1986/rm-hacks#244]
When cutting a selection, the button to clear the clipboard appears in the bottom right corner.

I often hit that with the side of my hand before I'm done copying.

If the button could be moved to another place (the top of the screen or left side for right handed mode), this would be a great improvement.

Thanks for your work!

**Comment by hakunamatatarr** [comment]
I am not sure if I should open another issue for that because it is slightly different but related:
The "copied to clipboard" bar goes over the whole width of the screen and covers the lowest button in the toolbar (for notebook settings, search, ...). Could you change it, either that the width of the bar is less or that the toolbar is on top of the black copied bar?

**Comment by atngames** [comment]
This has been fixed during the work on splitdoc. It has been included in alpha 5
I am closing this issue ;)

**Comment by atngames** [comment]
Closing as this is fixed in release 0.0.10
