### ISSUE TITLE
Adding horizontal space in the middle of the notebook

### ISSUE THREAD

**Issue by dafxy** [mb1986/rm-hacks#255]
It would be extremely useful if there were a way to add space anywhere on an existing page without having to use the select tool to select and drag the content. Something like this:

![tmp](https://github.com/mb1986/rm-hacks/assets/112355023/513ba174-a033-4cd2-bf65-68f71583d1fe)

**Comment by RedTartan04** [comment]
Oh YES :) One of these things you wonder why heck the it's not implemented by rM.
Ideally I'd like to be able to drag the split manually to where I need it.

Question is what happens if you drag the bottom of existing content over the bottom edge of the page
a) extends "continous" page - I personally wouldn't like that because I don't want extended pages at all
b) hits the bottom edge and wont go further - my preference

**Comment by chucktomasi** [comment]
I would find this useful. As a user of recalendar.me, I often start my day by lining up my appointments. As is often the case, calendars change throughout the day and someone adds something. This feature would make it easy to place new content in the middle of the day. I can see it being useful for other note taking use cases as well.

**Comment by PepikVaio** [comment]
I finally understand what you want :)
That would be quite a useful feature :)

How would one set how much space to add?

**Comment by dafxy** [comment]
One idea would be to select the tool and then tap the screen and drag the amount of space to add. This would be ideal, but I am not sure if this is feasible.

Another option would be to have a submenu in the tool, like those that appear for other tools, and one could select the amount of "lines" to add in the submenu: 3, 6, 9, or something like that. Then, tapping on the screen would add the space selected. The trick part here is to keep the writing aligned with the notebook lines after the space is added. So maybe one could select between adding 2,6,9 small or large lines in the submenu, and the space added could match the default size of the remarkable template of small and large lines as closely as possible.

I would also allow redo and auto de-select the tool after the line is added, that is, automatically switch to the previous tool used, to avoid adding space unintentionally by tapping the screen after the space is added.

**Comment by RedTartan04** [comment]
I'm not sure fixed amounts of space would fit all use cases, though it's a good idea if you use the built-in templates and it's a quick way with a minimal amount of interaction.

I for example mostly use a blank background and use different amounts of space to structure my notes, so for me dragging the space would be the only really useful way. 


(see also https://github.com/mb1986/rm-hacks/issues/255#issuecomment-1949911167)

**Comment by dafxy** [comment]
I think this solution would be great because it would add three functionalities at once. One could  shift the content below the line down  (add horizontal space), up (remove horizontal space), or remove the content below the line entirely.

**Comment by atngames** [comment]
@mb1986 I remember a POC for this exact thing, right?

**Comment by mb1986** [comment]
Yes, you are right, the poc was about selecting programmatically and we can do that.

**Comment by dafxy** [comment]
Any chance to get this working on the new release?

**Comment by builder-main** [comment]
Could this be implemented by and enhancement of the selection tool instead of create a new one ? Because adding a new space is : 
1. Selecting anything below
2. Move it down.

What I could suggest is : 
A.  Long press a point with selection tool.
B.  Select anything that is right and below the selected point.
C. Move around at will.

The thing is step B is subject to everyone usecase. But Right+Below would do what people want here.

**Comment by builder-main** [comment]
In my sens a manual full width setting is not necessary, just press on the left of the screen. 
Probably we should add a threshold so that any point below 5px of the screen will activate full-width / full-height selection
I think the interesting settings would be a Right/Left and Above/Below setting.

**Comment by RedTartan04** [comment]
Necessary no,  but 99% of my use case :) and more convenient. You don't have to mentally project the downward line to make sure you catch everything, when you just want to add horizontal space.
Also I find it a little akward (as a right-handed person) to tap left on the page to trigger a selection range which is then under my hand. Usually I draw selections in a way where I end at a point where I can see all of what I've selected.
Therefore I'd rather long press on the right side of a page to select everything below.
Your rectangular selection offers more flexibility but also more complexity. Hence I'd prefer settings.

**Comment by atngames** [comment]
And why not enhancing selection with some small icons that would allow to select all to the left from here, all to the bottom from here, and so on ? Those would just enlarge the existing selection

**Comment by dafxy** [comment]
I found a very simple way to do this, by accident. The text tool can add or remove horizontal space in the middle of the document, also moving up or down the handwritten notes. We just need to place the text tool prompt at the place we want to add or remove space and hit enter or backspace. For some  templates with rules, hitting enter or backspace three times gets the text down and realigned.
