### ISSUE TITLE
Option to remove Connect options for non-subscribers?

### ISSUE THREAD

**Issue by RedTartan04** [mb1986/rm-hacks#269]
A feature wish/suggestion to make the UI less annoying for "offliners" :)
As shown in the screenshot, would be nice to get rid of the Connect menu options and the (a) icon on the copy-paste popup. 
Also an additional options to hide the (T) for typed text which I never use?

![Screenshot_20240227_203718](https://github.com/mb1986/rm-hacks/assets/99086095/3e8fcc3e-db9d-4a15-8bb3-818b586f0b25)

**Comment by cool9333** [comment]
"Also an additional options to hide the (T) for typed text which I never
use"

Yes, please.

**Comment by mb1986** [comment]
I don't know how to remove this one:
![image](https://github.com/mb1986/rm-hacks/assets/1386931/619a77b5-499b-400c-be1c-5ef4af9bf3c3)

Everything else seems to be removed :)

**Comment by RedTartan04** [comment]
🤡 This makes an old "offliner" very happy 😎

**Comment by RedTartan04** [comment]
man, you're so fast :-)

![Screenshot_20240302_203521](https://github.com/mb1986/rm-hacks/assets/99086095/3c83ae2c-c8b6-42a1-a6a2-368c871d4c6c)

**Comment by knox-dawson** [comment]
I love (LOVE) not seeing the Text button any more. Text editors have been around since forever.  But can they give us a usable one? No.

Rant aside, and not sound greedy, I'm a connect subscriber but I DON'T use any of those features that would be grayed out if I weren't.  So can I make them disappear too, please?  Pretty please?

**Comment by RedTartan04** [comment]
oh, do the options not work if the rM is Connected?
