### ISSUE TITLE
0.0.9 in 3.9.5.2026: Can't minimize toolbar

### ISSUE THREAD

**Issue by regrubtaf** [mb1986/rm-hacks#270]
Thank you for updating the hacks for OS v.3.9.5.2026 for the rM2.  For some reason, I can't minimize the toolbar unless I first toggle "All Gestures" off.  When that option is toggled on, the bar is always there.  I like the thinner toolbar by the way. Thanks for that!

**Comment by mb1986** [comment]
Could you please be a little bit more precise in terms of what you mean by "can't minimize the toolbar"? Are you referring to the hidden button which closes the toolbar? If so, there is an option in the hacks configuration (Toolbar Configuration -> Hide toolbar header). The button is hidden by default because it is not needed when you use gesture to toggle the toolbar.

**Comment by regrubtaf** [comment]
Yes. I meant closing the toolbar.  I can confirm that the gesture to close the toolbar still works, but I thought that in v. 0.0.9 for OS v.3.9.3, there was still a button to close the toolbar with gestures on.  If the hacks are working as intended, then I will close or delete this issue. Thanks for the quick response!

**Comment by mb1986** [comment]
Yes, you may enable this button in the settings as I've mentioned above (Toolbar Configuration -> Hide toolbar header).

**Comment by regrubtaf** [comment]
@mb1986, Understood. Thanks!
