### ISSUE TITLE
Back to old layout

### ISSUE THREAD

**Issue by PepikVaio** [mb1986/rm-hacks#341]
Please, after update fw 3.12 will be this layout. 
Can you hold old layout?

![image](https://github.com/mb1986/rm-hacks/assets/36114753/ce5bf2fb-e950-4555-bfc7-c3b660b55a02)

**Comment by atngames** [comment]
I don't know about this one. I am afraid that it would be difficult to maintain. 
I would like to have @mb1986 's insights on this.

**Comment by PepikVaio** [comment]
OK, thank you for effort.

**Comment by Eeems** [comment]
I would not recommend maintaining a complete UI rewrite. It will add a lot of work to supporting each new OS version, and only get harder as they change more things.

**Comment by PepikVaio** [comment]
I guess you're right. But the new layout isn't good.

**Comment by Eeems** [comment]
> I guess you're right. But the new layout isn't good.

That's subjective. You may not like it, but others may prefer it. I would recommend providing rM with feedback that you don't prefer it, with concrete information about what you don't like, why you don't like it (usability etc). As well as options as to what could be changed to make it more tolerable for you. It may also be worth doing some self-reflection to make sure that the reason you don't like it isn't just because of resistance to change.

**Comment by PepikVaio** [comment]
Hey, you're right, and I agree with you. It's not so much ugly as it is impractical. 

As many reviews on the internet - I have to tap senselessly 2x when I want to create a workbook, folder,...

**Comment by RedTartan04** [comment]
It's distracting because it overlays the thumbnail view. Very poor design.

**Comment by PepikVaio** [comment]
I'm closing, you get used to it :)
We have a lot of other problems to deal with.

@Eeems is right, it would probably be difficult to maintain 2 looks over and over again.
