### ISSUE TITLE
Add support for bookmarks

### ISSUE THREAD

**Issue by lmwgv** [mb1986/rm-hacks#43]
Thanks a lot for bringing this project back to life.

The one feature that keeps me from updating to v3 is bookmarks, I work with several long reference books that cannot be used conveniently without bookmarks.

I don't know quite how ddvk did it, but from outside it seems that the hack kept a ".bookm" file alongside each document, with the bookmark information.

**Comment by Tridens92** [comment]
I also really appreciate the bookmark feature.

**Comment by pr0fsmith** [comment]
YES PLEASE INCLUDE THIS FEATURE!!!!!

**Comment by fcr** [comment]
I am also waiting for this. This is also the main feature keeping me in V2

**Comment by mb1986** [comment]
I've included this as a feature for v0.0.7, but we'll see how much time it takes. It is certainly doable.

**Comment by pr0fsmith** [comment]
Thank you so much. I really appreciate your work on this.

Nov 24, 2023 9:35:56 p.m. Michał Blinkiewicz ***@***.***>:

**Comment by rudy0ne** [comment]
This is exciting, I hope we can rename the bookmarks : )

**Comment by Tridens92** [comment]
I'm just glad they're on the roadmap. Thanks so much for your great work!

**Comment by pr0fsmith** [comment]
I'm really hoping to be able to import my existing bookmarks I created with ddvk hacks

Dec 11, 2023 1:55:59 p.m. Michał Blinkiewicz ***@***.***>:

**Comment by Tridens92** [comment]
However, I would LOVE to see some work done with labels.  My first wish would be to sort them.  Sort options could be:

-Alphabetical (this is the one I'd use as default / most often
-Creation date
-Frequency (number of pages that contain that label) 

On the latter one, perhaps this info could be included next to the label in label view in parenthesis, like:
Meetings (34)

I'd also love a more elegant way to delete labels.

Thanks again for all of your work on this project!

**Comment by PepikVaio** [comment]
The labels are great, but as "Tridens 92" says, that's a lot of taps on the display.

I would like to improve the label experience, so I opened a request: #72

**Comment by mb1986** [comment]
Thanks for the explanation. I'll try to bring the ddvk's bookmarks back first. It means old bookmarks should reappear :)

**Comment by mb1986** [comment]
I am currently working on the bookmarks feature and would appreciate some clarifications from you:

1. Does tapping on the top corner (the one opposite to the toolbar) toggle a bookmark?
2. Does the toolbar display a black or white bookmark icon depending on whether the page is bookmarked?
3. What happens when the bookmark icon on the toolbar is tapped?
4. Where should one long-press to rename a bookmark?
5. When adding pages, should all bookmarks after that page be moved accordingly?
6. Do the left and right arrows on the toolbar jump to the previous or next bookmarked page?
7. What does the 'L' symbol mean in the bookmarks list?
8. How many bookmarks can be displayed in the bookmarks list?
9. Should the list appear after tapping the bookmark icon on the toolbar?
10. Is there anything else I should be aware of?

**Comment by PepikVaio** [comment]
Keep the left-handers in mind :)
I couldn't use DDVK bookmarks because I bookmarked each page.
Same as the disabling cross from reMarkable - Which I have disabled and it's a hoot :)

**Comment by mb1986** [comment]
Maybe I should keep the bookmark icon always on the right hand side (?).

**Comment by PepikVaio** [comment]
I guess it's okay to have the bookmark icon on the other side than the reMarkable panel.
There just can't be a gesture to create the bookmark.
I'm fine with the bookmark being made with just the icon in the bar.
What about the others???

**Comment by rudy0ne** [comment]
I never tried ddvk, but based on what I observed in [this video](https://youtu.be/kmOAfpgn5GM?t=639):


> 2. Does the toolbar display a black or white bookmark icon depending on whether the page is bookmarked?

It probably should if you were to make the icon on the top corner optional.

> 4. Where should one long-press to rename a bookmark?

On the list itself would be great, especially to rename them all without having to jump to every bookmarked page.

And what about long-pressing the toolbar icon to bookmark the page?

**Comment by dreadful-brain** [comment]
I have worked a lot with DDVKs Bookmarks, I will answer the questions from the perspective of "how should it work" rather than "how did DDVKs Bookmarks work":

> 1. Does tapping on the top corner (the one opposite to the toolbar) toggle a bookmark?
Yes
> 2. Does the toolbar display a black or white bookmark icon depending on whether the page is bookmarked?
Yes
> 3. What happens when the bookmark icon on the toolbar is tapped?
A list of Bookmarks in this document opens and you can jump directly by selecting another bookmark
> 4. Where should one long-press to rename a bookmark?
On the bookmark icon in the top corner
Nice to have: in the list of bookmarks that pops up pressing bookmark icon in toolbar - so you don't have to switch to the page to rename the bookmark.
> 5. When adding or removing pages, should all bookmarks after that page be moved accordingly?
Definitely yes
> 6. Do the left and right arrows on the toolbar jump to the previous or next bookmarked page?
No, these should navigate pages sequentially, as this is a great function for turning pages with the stylus. 
Nice to have: Provide an option to choose between "page turns" or "bookmark jumps" in settings 
> 7. What does the 'L' symbol mean in the bookmarks list?
"Last page". This is handy on large PDFs, a "F" for First page would also be useful.
> 8. How many bookmarks can be displayed in the bookmarks list?
DDVK opened up multiple colums depending on screen orientation, so there were a lot.
At first show them in one column until screen is almost covered - leave some free space for gesture detection - and then open a second row and so on.
> 9. Should the list appear after tapping the bookmark icon on the toolbar?
Yes - see question 3
> 10. Is there anything else I should be aware of?
In the DDVK implementation, the boxes for the bookmarks in the list were all the same size, which resulted in the labels being cut off when a second column of bookmarks was displayed.
Perhaps the bookmark boxes could be made as wide as the longest label. This would result in fewer columns of bookmarks being displayed on the screen, but would significantly improve readability.

**Comment by fcr** [comment]
Here is an example of DDVKs bookmarks 
![Bookmarks](https://github.com/mb1986/rm-hacks/assets/103160/ba59a4ec-8cc2-4a62-b61d-d40f7f2c824f)

**Comment by mb1986** [comment]
Thank you! Now I understand how it should work.

**Comment by rudy0ne** [comment]
> > 6. Do the left and right arrows on the toolbar jump to the previous or next bookmarked page?
> 
> Those arrows (as found in ddvk/remarkable-hacks) are only slightly related to bookmarks: They allow to go backward and forward within the **navigation history**.
> 
> This includes any navigation performed within a document by forward/backward swipes and (in M/reading mode) taps, page slider, page overview, table of contents, PDF links, jump to page number (input via number pad), and finally also bookmarks.

These "navigation history" back and forward buttons would be very useful.

**Comment by PepikVaio** [comment]
> > > 6. Přeskakují levé a pravé šipky na panelu nástrojů na předchozí nebo další stránku se záložkou?
> > 
> > 
> > Tyto šipky (jak je najdete v ddvk/remarkable-hacks) se záložkami jen málo souvisí: Umožňují přecházet zpět a vpřed v rámci **historie navigace** .
> > To zahrnuje jakoukoli navigaci prováděnou v dokumentu přejetím vpřed/vzad a (v režimu M/čtení) klepnutím, posuvníkem stránky, přehledem stránky, obsahem, odkazy na PDF, skokem na číslo stránky (zadání pomocí numerické klávesnice) a nakonec také záložky.
> 
> Tato tlačítka "historie navigace" zpět a vpřed by byla velmi užitečná.

The request has already been created
https://github.com/mb1986/rm-hacks/issues/26

**Comment by PepikVaio** [comment]
> * Když klepnete na pravý horní roh pro přidání nebo odebrání záložky, když je seznam záložek otevřený, seznam se dynamicky aktualizuje.
> * Zobrazení a přepínání záložek v pravém horním rohu lze vypnout pomocí přepínače nastavení. Záložky lze stále přepínat dlouhým stisknutím ikony na panelu nástrojů.

Don't give the gesture of adding bookmarks - it kills me :)
It's very important to be able to turn off the gesture but keep the bookmark add feature in a different way.

**Comment by rudy0ne** [comment]
> Here is an example of DDVKs bookmarks ![Bookmarks](https://private-user-images.githubusercontent.com/103160/293321412-ba59a4ec-8cc2-4a62-b61d-d40f7f2c824f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzgwMTcsIm5iZiI6MTcwMzg3NzcxNywicGF0aCI6Ii8xMDMxNjAvMjkzMzIxNDEyLWJhNTlhNGVjLThjYzItNGE2Mi1iNjFkLWQ0MGY3ZjJjODI0Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxOTIxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yjk3ZTA0NWNiYzUxNTQwNzQ1NTU5YTVmNTY5OTBlNzc0YTZjYzZiZWU1MmU5ZWZlNmMxYjA2YzY0YmVkNTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ywOKncjbzvYYDuwARqcO5hgngPMlT9XqHZH1HzmDFqM)

It looks like a Bingo card rather than a bookmarks list.

**Comment by mb1986** [comment]
I'm just reproducing this bingo card 😁

**Comment by cool9333** [comment]
Total noob here. I wish there was some way to edit the passcode screen. Maybe add graphics, change button styles, high contract w/ dark back ground & light keys. Not sure if this even possible but thought I would ask.

Thanks mb1986 for all of the work you put into this!

**Comment by rudy0ne** [comment]
> I'm just reproducing this bingo card 😁

Nooo 😭 What about aligning the numbers to the top left corner so it's less Bingo-like.

**Comment by mb1986** [comment]
I am changing the layout a little bit, will show you something possibly tomorrow.

**Comment by rudy0ne** [comment]
That's beautiful!!

**Comment by mb1986** [comment]
Please consider backing you bookmarks up. For example using `scp`:

```sh
scp 'root@<rm_device_ip>:/home/root/.local/share/remarkable/xochitl/*.bookm' ./
```
