### ISSUE TITLE
Gesture to swap tools

### ISSUE THREAD

**Issue by Finardi-FS** [mb1986/rm-hacks#9]
It would be nice to swap the pen with the previous tool (as happens with ddvk-hack). Maybe it could be done using 4-finger tap or even with the right button using the rm1 (or left button for the ereaser).

Thanks for your work and your time!!

**Comment by mb1986** [comment]
Thanks for the suggestion, yes it would be possible but it has to wait for #11 because we will need to store two last tools for each notebook. For now we could do it similarly to ddvk's implementation - it will not be remembered after notebook close.

**Comment by mb1986** [comment]
In v0.0.3, there is an option to perform this action by clicking the Lamy pen button.

**Comment by mb1986** [comment]
Could you please verify that it works as expected?

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.4
```

**Comment by Finardi-FS** [comment]
Unfortunately I can't try it at the moment because I only left beta mode after having version 3.8.0.1944 (and I also don't have a lamy pen).

Could you tell me how to roll back? 

Otherwise I'll be happy to give you my feedback for next updates!

**Comment by mb1986** [comment]
The v0.0.4 (not officially released yet) brings two new gestures (no need  to use a Lamy pen):

- Gesture to switch between the last two tools: swipe one finger down in the top left corner.
- Gesture to switch between the writing tool and eraser: swipe one finger up in the top left corner.

I regards to rolling back an similar stuff I'd recommend using https://github.com/ddvk/remarkable-update :)

**Comment by dreadful-brain** [comment]
Patch 0.0.4 works greate (rM2 3.7.0.1930 + Lamy EMR). I tested in landscape and portrait.
IMO the swipe gestures (switching pens and eraser) work much better than in original ddvk hacks.
Awesome work!
The only thing that is a bit annoying is the blue texts in the install script.
Since on Windows the default background color of the most common SSH tool Putty is black, you have to change it first to be able to read the questions. 
For me this is not a problem, because I use Putty regularly, but it could be a hurdle for some people. 
Suggestion: use cyan (0,255,255) instead of blue text.

**Comment by mb1986** [comment]
Happy to hear that! Good catch on the color; I hadn't thought about that while using Linux all the time. I'll change the color soon.
